name: Build and deploy ASP.NET MVC 4 app to Azure Web App - Mvc4AzureApp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet packages
        run: nuget restore Mvc4AzureApp.sln

      - name: Build and publish Web Project
        run: msbuild Mvc4AzureApp/Mvc4AzureApp.csproj ^
          /p:Configuration=Release ^
          /p:DeployOnBuild=true ^
          /p:WebPublishMethod=FileSystem ^
          /p:DeleteExistingFiles=True ^
          /p:publishUrl="${{ github.workspace }}\publish"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ASP-app
          path: ${{ github.workspace }}\publish\

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ASP-app
          path: ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B2D415F966A14E36A9F343C28FA9C389 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8160D4FA9BCF49749A7A3E48CA067F4F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9C11167B22714095B13B2196827CB19F }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Mvc4AzureApp'
          slot-name: 'Production'
          package: ./publish
